name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python -m pytest


# The file introduces a new GitHub Action named Continuous Integration that is triggered on push,
# meaning that everytime a developer pushes a code to a branch where this file exists.
# The action then runs the following steps in the order of their definition on an ubuntu-latest container:
# 1- Check out to the current GGit branch.
# 2- Set up Python on the container.
# 3- Install the Python dependencies of the Bank Account app defined in requirements.txt.
# 4- Run the unit tests using Pytest.

# 5- To run the tests when creating a new pull request we update the array of triggers to add pull_request:
# previously -  on: [push], now - on: [push, pull_request]